name: push
on: 
  push:
    branches:
      - master
      - main
    tags:        
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}
      KOSLI_OWNER: smuzychu    
    steps:

    - name: set repo name
      shell: bash
      run: | 
        echo "REPOSITORY_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV    

    - name: setup kosli
      uses: kosli-dev/setup-cli-action@v1
    - name: declare pipeline
      run: kosli pipeline declare --pipeline ${{ env.REPOSITORY_NAME }} -t pull-request,artifact

    - name: report pull request evidence
      run: kosli pipeline artifact report evidence github-pullrequest ghcr.io/${{ github.repository_owner }}/${{ env.REPOSITORY_NAME }}:${{ github.sha }} -t docker -p ${{ env.REPOSITORY_NAME }} --github-token ${{ secrets.GITHUB_TOKEN }} -e pull-requests        
              
    - name: checkout code
      uses: actions/checkout@v2
    - name: Docker Login
      uses: docker/login-action@v1.12.0
      with:
        registry: 'ghcr.io'
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build container image and push
      uses: docker/build-push-action@v2.7.0
      with:
        context: .
        file: ./${{ env.PROJECT_DIR }}/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{ env.REPOSITORY_NAME }}:${{ github.sha }}
          ghcr.io/${{ github.repository_owner }}/${{ env.REPOSITORY_NAME }}:latest
          ghcr.io/${{ github.repository_owner }}/${{ env.REPOSITORY_NAME }}:${{ github.ref_name }}       

    - name: report image artifact
      run: kosli pipeline artifact report creation ghcr.io/${{ github.repository_owner }}/${{ env.REPOSITORY_NAME }}:${{ github.sha }} -t docker -p ${{ env.REPOSITORY_NAME }}

    